eZTest:
    pattern: /test/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:test
        contentId: 102
    requirements:
        contentId: \d+

eZTestWithLegacy:
    pattern: /test/legacy/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:testWithLegacy
        contentId: 102

eZHelloWorld:
    pattern: /helloWorld
    defaults:
        _controller: eZDemoBundle:Demo:helloWorld
        name: World

eZHelloWorldCached:
    pattern: /helloWorldCached
    defaults:
        _controller: eZDemoBundle:Demo:helloWorldCached

eZHelloWorldTwig:
    pattern: /helloWorldTwig
    defaults:
        _controller: eZDemoBundle:Demo:helloWorldTwig

eZHelloWorldTwigCached:
    pattern: /helloWorldTwigCached
    defaults:
        _controller: eZDemoBundle:Demo:helloWorldTwigCached

eZEditorial:
    pattern: /Editorial/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:editorial

eZSetupLegacy:
    pattern: /ezdemo_site_admin/setup/info
    defaults:
        _controller: eZDemoBundle:Setup:info

