<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezwebin_banners",
                     "development" => false,
                     "summary" => "Demo content (banners) for the ezwebin extension",
                     "description" => "This package contains the following nodes :\nBanners - subtree\n",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "contentobject",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "4.7.0",
                                           "named-version" => "4.7" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1176207698",
                                           "host" => "packages.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1176207698",
                                                  "person" => "Administrator User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array( "9afb84fc725496e93b4c0413c9994f9e" => array( "original-path" => "var/storage/images/media/banners/woman_communities/1377-1-eng-GB/woman_communities.jpg",
                                                                                               "package-path" => "simplefiles/84f1da4c.jpg" ),
                                                  "28571362e8ac1b5b92267057b9b757ef" => array( "original-path" => "var/storage/images/media/banners/woman_frontpage/1382-6-eng-GB/woman_frontpage.jpg",
                                                                                               "package-path" => "simplefiles/83ea7f16.jpg" ),
                                                  "c5bd8c7efa8d3e0ddfd3a42cb8f70444" => array( "original-path" => "var/storage/images/media/banners/woman_products/1387-1-eng-GB/woman_products.jpg",
                                                                                               "package-path" => "simplefiles/99bedbaa.jpg" ),
                                                  "4ae98c0da61ce4a94886d3955d6609b2" => array( "original-path" => "var/storage/images/media/banners/woman_partners/1663-1-eng-GB/woman_partners.jpg",
                                                                                               "package-path" => "simplefiles/24ec46f7.jpg" ),
                                                  "edd7d3b61c594004df1f81bf1ec72ee9" => array( "original-path" => "var/storage/images/media/banners/pencils_support/1744-1-eng-GB/pencils_support.jpg",
                                                                                               "package-path" => "simplefiles/50dbb211.jpg" ),
                                                  "c21b8a15309768adf426301e831ca6cd" => array( "original-path" => "var/storage/images/media/banners/woman_training/1749-1-eng-GB/woman_training.jpg",
                                                                                               "package-path" => "simplefiles/47966db1.jpg" ),
                                                  "3d26cd8f63aac6ec6774a519bbcb452e" => array( "original-path" => "var/storage/images/media/banners/woman_solutions/1908-2-eng-GB/woman_solutions.jpg",
                                                                                               "package-path" => "simplefiles/944390f8.jpg" ),
                                                  "941156c06bd6bf1956cf5dca16bd2d85" => array( "original-path" => "var/storage/images/media/banners/only-lyon-banner/1158-1-eng-US/Only-Lyon-Banner.jpg",
                                                                                               "package-path" => "simplefiles/d24c09fc.jpg" ) ),
                     "version-number" => "1.10",
                     "release-number" => "0",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezcontentobject",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "contentobjects",
                                                "sub-directory" => "ezcontentobject" ) ),
                     "uninstall" => array( array( "type" => "ezcontentobject",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "contentobjects",
                                                  "sub-directory" => "ezcontentobject" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/eZ-systems";
?>
