<?php
// This file contains functions which are common to all compiled templates.
//
// NOTE: This file is autogenerated and should not be modified, any changes will be lost!

define( "EZ_TEMPLATE_COMPILER_COMMON_CODE", true );

if ( !isset( $namespaceStack ) )
    $namespaceStack = array();

if ( !function_exists( 'compiledfetchvariable' ) )
{
    function compiledFetchVariable( $vars, $namespace, $name )
    {
        $exists = ( array_key_exists( $namespace, $vars ) and
                    array_key_exists( $name, $vars[$namespace] ) );
        if ( $exists )
        {
            return $vars[$namespace][$name];
        }
        return null;
    }
}
if ( !function_exists( 'compiledfetchtext' ) )
{
    function compiledFetchText( $tpl, $rootNamespace, $currentNamespace, $namespace, $var )
    {
        $text = '';
        $tpl->appendElement( $text, $var, $rootNamespace, $currentNamespace );
        return $text;
    }
}
if ( !function_exists( 'compiledAcquireResource' ) )
{
    function compiledAcquireResource( $phpScript, $key, &$originalText,
                                      $tpl, $rootNamespace, $currentNamespace )
    {
        include( '' . $phpScript );
        if ( isset( $text ) )
        {
            $originalText .= $text;
            return true;
        }
        return false;
    }
}
if ( !function_exists( 'compiledfetchattribute' ) )
{
    function compiledFetchAttribute( $value, $attributeValue )
    {
        if ( is_object( $value ) )
        {
            if ( method_exists( $value, "attribute" ) and
                 method_exists( $value, "hasAttribute" ) )
            {
                if ( $value->hasAttribute( $attributeValue ) )
                {
                    return $value->attribute( $attributeValue );
                }
            }
        }
        else if ( is_array( $value ) )
        {
            if ( isset( $value[$attributeValue] ) )
            {
                return $value[$attributeValue];
            }
        }
        return null;
    }
}
?>
