<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezwebin_design_gray",
                     "development" => false,
                     "summary" => "eZ Publish Website Interface design (gray)",
                     "description" => "This site style package contains the design for the Website Interface",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "sitestyle",
                     "extension" => false,
                     "install_type" => "import",
                     "ezpublish" => array( "version" => "4.7.0",
                                           "named-version" => "4.7" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1162333368",
                                           "host" => "packages.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1162333368",
                                                  "person" => "Administrator User",
                                                  "email" => "jkn@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array( "default" => array( array( "name" => "thumbnail.png",
                                                                      "subdirectory" => "",
                                                                      "type" => "thumbnail",
                                                                      "role" => "",
                                                                      "role-value" => "",
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "var/storage/temp/thumbnail.png",
                                                                      "file-type" => "",
                                                                      "design" => "",
                                                                      "md5" => "d0a098ad93432761ff270ea553e549d4" ),
                                                               array( "name" => "site-colors.css",
                                                                      "subdirectory" => "",
                                                                      "type" => "file",
                                                                      "role" => "",
                                                                      "role-value" => "",
                                                                      "variable-name" => "sitecssfile",
                                                                      "path" => "var/storage/temp/site-colors.css",
                                                                      "file-type" => "",
                                                                      "design" => "",
                                                                      "md5" => "74c783c0aff85a585311e3ce31cdac29" ),
                                                               array( "name" => "classes-colors.css",
                                                                      "subdirectory" => "",
                                                                      "type" => "file",
                                                                      "role" => "",
                                                                      "role-value" => "",
                                                                      "variable-name" => "classescssfile",
                                                                      "path" => "var/storage/temp/classes-colors.css",
                                                                      "file-type" => "",
                                                                      "design" => "",
                                                                      "md5" => "1a1ed64f28bec7d535b69207c81ad026" ) ) ),
                     "simple-file-list" => array(),
                     "version-number" => "1.10",
                     "release-number" => "0",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "",
                                                "sub-directory" => "" ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "",
                                                  "sub-directory" => "" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/eZ-systems";
?>
